os: linux
dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

jobs:
  fast_finish: true

install: pip install coveralls

script:
  - coverage run --source=officeextractor -m unittest discover tests
  - coverage report

after_success: coveralls
