os: linux
dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"

jobs:
  fast_finish: true

install: pip install coveralls

script: python -m unittest discover tests

after_success: coveralls
